"""Provide Dijkstra-based pathfinding for Fly-in maps."""

from __future__ import annotations

import heapq
from typing import TypeAlias

from src.Models.graph import Graph
from src.Utils.connection_key import make_connection_key

PathCost: TypeAlias = tuple[int, int]


class PathNotFoundError(Exception):
    """Raised when no valid path can be found between start and end."""


class Dijkstra:
    """Find valid low-cost paths through a Fly-in graph.

    The pathfinder avoids blocked zones and minimizes movement turns.
    Among paths with the same movement cost, it prefers paths containing
    more priority zones.
    """

    def __init__(self, graph: Graph) -> None:
        """Initialize the pathfinder with a graph."""
        self.graph = graph

    def find_path(self) -> list[str]:
        """Return the best path from the start zone to the end zone.

        Raise:
            PathNotFoundError: If no valid path exists.
        """
        path = self._find_best_path_or_none()

        if path is None:
            raise PathNotFoundError("No valid path from start to end.")

        return path

    def find_paths(self, max_paths: int = 6) -> list[list[str]]:
        """Return several valid simple paths from start to end.

        The first path is the best path found by Dijkstra. Additional paths
        are generated by temporarily banning edges and zones from previous
        paths to encourage alternative routes without loops.
        """
        first_path = self._find_best_path_or_none()

        if first_path is None:
            return []

        paths: list[list[str]] = [first_path]
        candidates: list[tuple[PathCost, int, list[str]]] = []
        seen: set[tuple[str, ...]] = {tuple(first_path)}
        sequence = 0

        while len(paths) < max_paths:
            sequence = self._add_candidates_from_base_path(
                paths,
                candidates,
                seen,
                sequence,
            )

            if not candidates:
                break

            _, _, next_path = heapq.heappop(candidates)
            paths.append(next_path)

        return paths

    def find_path_between(
        self,
        start_zone: str,
        end_zone: str,
        banned_edges: set[frozenset[str]],
        banned_zones: set[str],
    ) -> list[str] | None:
        """Return the lowest-cost valid path between two zones.

        The search ignores blocked zones, banned zones, and banned edges.
        Return None when the destination cannot be reached.
        """
        distances: dict[str, PathCost] = {start_zone: (0, 0)}
        previous: dict[str, str] = {}
        queue: list[tuple[int, int, str]] = [(0, 0, start_zone)]

        while queue:
            movement_cost, priority_cost, current_zone = heapq.heappop(queue)
            current_cost = (movement_cost, priority_cost)

            if current_cost != distances.get(current_zone):
                continue

            if current_zone == end_zone:
                return self._reconstruct_path(
                    previous,
                    start_zone,
                    end_zone,
                )

            self._visit_neighbors(
                current_zone=current_zone,
                current_cost=current_cost,
                distances=distances,
                previous=previous,
                queue=queue,
                banned_edges=banned_edges,
                banned_zones=banned_zones,
            )

        return None

    def _find_best_path_or_none(self) -> list[str] | None:
        """Return the best path from graph start to end, or None."""
        return self.find_path_between(
            start_zone=self.graph.start,
            end_zone=self.graph.end,
            banned_edges=set(),
            banned_zones=set(),
        )

    def _visit_neighbors(
        self,
        current_zone: str,
        current_cost: PathCost,
        distances: dict[str, PathCost],
        previous: dict[str, str],
        queue: list[tuple[int, int, str]],
        banned_edges: set[frozenset[str]],
        banned_zones: set[str],
    ) -> None:
        """Evaluate all valid neighbors from the current zone."""
        for neighbor in self.graph.get_neighbors(current_zone):
            if not self._can_visit_neighbor(
                current_zone,
                neighbor,
                banned_edges,
                banned_zones,
            ):
                continue

            zone_cost = self._zone_cost(neighbor)
            next_cost = (
                current_cost[0] + zone_cost[0],
                current_cost[1] + zone_cost[1],
            )

            if next_cost >= distances.get(neighbor, (10**18, 10**18)):
                continue

            distances[neighbor] = next_cost
            previous[neighbor] = current_zone
            heapq.heappush(queue, (*next_cost, neighbor))

    def _add_candidates_from_base_path(
        self,
        paths: list[list[str]],
        candidates: list[tuple[PathCost, int, list[str]]],
        seen: set[tuple[str, ...]],
        sequence: int,
    ) -> int:
        """Generate alternative path candidates from the latest path."""
        base_path = paths[-1]

        for index in range(len(base_path) - 1):
            sequence = self._add_candidate_from_spur(
                paths,
                candidates,
                seen,
                sequence,
                index,
                base_path,
            )

        return sequence

    def _add_candidate_from_spur(
        self,
        paths: list[list[str]],
        candidates: list[tuple[PathCost, int, list[str]]],
        seen: set[tuple[str, ...]],
        sequence: int,
        index: int,
        base_path: list[str],
    ) -> int:
        """Generate one candidate path from a root and spur zone."""
        root_path = base_path[: index + 1]
        spur_zone = root_path[-1]

        banned_edges = self._get_banned_edges_for_root(
            paths,
            root_path,
            index,
        )
        banned_zones = set(root_path[:-1])

        spur_path = self.find_path_between(
            start_zone=spur_zone,
            end_zone=self.graph.end,
            banned_edges=banned_edges,
            banned_zones=banned_zones,
        )

        if spur_path is None:
            return sequence

        candidate_path = root_path[:-1] + spur_path
        candidate_key = tuple(candidate_path)

        if candidate_key in seen:
            return sequence

        seen.add(candidate_key)

        return self._push_candidate(
            candidates,
            sequence,
            candidate_path,
        )

    def _push_candidate(
        self,
        candidates: list[tuple[PathCost, int, list[str]]],
        sequence: int,
        candidate_path: list[str],
    ) -> int:
        """Push a candidate path into the priority queue."""
        sequence += 1

        heapq.heappush(
            candidates,
            (
                self._path_cost(candidate_path),
                sequence,
                candidate_path,
            ),
        )

        return sequence

    def _can_visit_neighbor(
        self,
        current_zone: str,
        neighbor: str,
        banned_edges: set[frozenset[str]],
        banned_zones: set[str],
    ) -> bool:
        """Return whether a neighbor can be visited by the search."""
        if neighbor in banned_zones or self.graph.is_blocked(neighbor):
            return False

        return (
            make_connection_key(current_zone, neighbor)
            not in banned_edges
        )

    def _zone_cost(self, zone_name: str) -> PathCost:
        """Return movement cost and priority tie-break cost for a zone."""
        priority_cost = 0 if self.graph.is_priority(zone_name) else 1
        return self.graph.get_movement_cost(zone_name), priority_cost

    def _path_cost(self, path: list[str]) -> PathCost:
        """Return the total movement and priority cost of a path."""
        movement_cost = 0
        priority_cost = 0

        for zone_name in path[1:]:
            zone_cost = self._zone_cost(zone_name)
            movement_cost += zone_cost[0]
            priority_cost += zone_cost[1]

        return movement_cost, priority_cost

    def _get_banned_edges_for_root(
        self,
        paths: list[list[str]],
        root_path: list[str],
        index: int,
    ) -> set[frozenset[str]]:
        """Return edges that would duplicate already known root paths."""
        banned_edges: set[frozenset[str]] = set()

        for known_path in paths:
            same_root = (
                len(known_path) > index
                and known_path[: index + 1] == root_path
            )

            if same_root:
                banned_edges.add(
                    make_connection_key(
                        known_path[index],
                        known_path[index + 1],
                    )
                )

        return banned_edges

    def _reconstruct_path(
        self,
        previous: dict[str, str],
        start_zone: str,
        end_zone: str,
    ) -> list[str]:
        """Reconstruct a path from the end zone back to the start zone."""
        path = [end_zone]

        while path[-1] != start_zone:
            path.append(previous[path[-1]])

        path.reverse()
        return path
